name: Pegg
favicon: null
layout_spectrum: 0.87017
typography_spectrum: 0.16164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6e5ed'
    - '#2e3067'
    - '#648d99'
    - '#7dd30e'
    - '#e04940'
  brandStrength: 0.5
  lightness: 0.7616488756611943
  saturation: 0.5221500240731984
  rhythmicContrast: 0.28576763113960624
purpose: []
