name: Pegg
favicon: null
layout_spectrum: 0.8936243685893714
typography_spectrum: 0.1834978696424514
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.10599292814731598
  lightness: 0.7616488756611943
  saturation: 0.5221500240731984
  rhythmicContrast: 0.28576763113960624
purpose: []
